rm `demisto-sdk json-to-outputs` example
`demisto-sdk json-to-outputs` command doesn't exist:

```bash
❯ demisto-sdk --version
You are using demisto-sdk 1.6.1.

❯ demisto-sdk json-to-outputs -h
Usage: demisto-sdk [OPTIONS] COMMAND [ARGS]...

Error: No such command 'json-to-outputs'.
```